{
 "title": "Warm Office",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "warmoffice_current_temperature", "legendFormat": "temperature" }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "warmoffice_state" }
   ]
  },
  {
   "title": "Office Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(warmoffice_current_temperature[5m])",
     "legendFormat": "current"
    },
    { "expr": "warmoffice_target_temperature", "legendFormat": "target" },
    { "expr": "warmoffice_thermostat_active", "legendFormat": "active" },
    { "expr": "warmoffice_thermostat_heating", "legendFormat": "heating" }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_current_temp[10m])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Motion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(warmoffice_motion_detected[5m])  ",
     "legendFormat": "motion"
    },
    { "expr": "warmoffice_presence", "legendFormat": "presence" }
   ]
  },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "warmoffice_state{name=\"\"}",
     "legendFormat": "state"
    }
   ]
  }
 ]
}